name: first

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: echo date +'%Y-%m-%d'
  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: echo Get-Date -Format "yyyy-MM-dd"
  job3:
    name: third job
    runs-on: macos-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: echo date +'%Y-%m-%d'
  job4:
    needs: [job1, job2, job3]
    name: fourth job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: echo date +'%Y-%m-%d' 